@startuml

actor       Customer       as customer
boundary    Homepage    as homepage
control     DisplayMyPage     as displaymypage
boundary    Mypage    as mypage
control     entergoals   as entergoals
control     setgoal  as setgoal
boundary      Goal      as goal
control     areGoalSet as areGoalSet
control showgoals as showgoals
control showInputOppurtunity as showInputOppurtunity


customer -> homepage:
homepage -> displaymypage : "Customer clicks mypage"
displaymypage -> mypage :
mypage -> entergoals :
entergoals -> setgoal : "customer enter goals"
setgoal -> goal :
goal -> areGoalSet :
areGoalSet -> showgoals : yes
OPT optional workflow
showgoals -> mypage :
end
areGoalSet -> showInputOppurtunity : no
ALT  alternative workflow
showInputOppurtunity -> mypage :
end



@enduml